//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TV.Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favoriteprogram
    {
        public int Id { get; set; }
        public Nullable<int> Person { get; set; }
        public Nullable<int> Program { get; set; }
    
        public virtual Person Person1 { get; set; }
        public virtual Program Program1 { get; set; }
    }
}
